import { describe, expect, test } from "bun:test";
import { buildConversation } from "../src/conversation.ts";

/**
 * Claude Code files some of its own records under the user's name, flagged: the compaction
 * summary (`isCompactSummary`) and meta records (`isMeta`) — command caveats, "continued
 * from another machine", a loaded skill's whole instructions. Shapes as measured in Tyler's
 * transcripts, 2026-09-23.
 */
const rows = (...records: object[]) => {
  const conversation = buildConversation("s", records.map((record) => JSON.stringify(record)), "claude");
  return conversation.order.map((id) => {
    const item = conversation.items[id]!;
    return item.kind === "material" ? ["material", item.material?.title, item.material?.detail?.slice(0, 40)] : [item.kind, item.text.slice(0, 40)];
  });
};
const user = (content: string, extra: object = {}) => ({ type: "user", uuid: Math.random().toString(36), message: { role: "user", content }, ...extra });

describe("Claude Code's own records are notes, not Tyler's words", () => {
  test("the compaction summary", () => {
    expect(rows(user("This session is being continued from a previous conversation that ran out of context.", { isCompactSummary: true })))
      .toEqual([["material", "Earlier conversation summarised", "This session is being continued from a p"]]);
  });

  test("meta records: a command caveat, a machine hand-off, a skill's instructions", () => {
    expect(rows(
      user("<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>", { isMeta: true }),
      user("This session is being continued from another machine.", { isMeta: true }),
      user("Base directory for this skill: /Users/t/.claude/skills/x", { isMeta: true }),
    )).toEqual([
      ["material", "Added by Claude Code", "Caveat: The messages below were generate"],
      ["material", "Added by Claude Code", "This session is being continued from ano"],
      ["material", "Added by Claude Code", "Base directory for this skill: /Users/t/"],
    ]);
  });

  test("what Tyler typed is still his, and a known wrapper keeps its own kind", () => {
    expect(rows(
      user("fix the header please"),
      user("<system-reminder>Plan mode is active.</system-reminder>", { isMeta: true }),
    )).toEqual([["user", "fix the header please"], ["material", "System note", "Plan mode is active."]]);
  });
});
