#!/bin/bash
# Resolve src/voice-requirements.in into the hashed lock conch installs for its
# natural voices (src/voice-requirements.txt). Run it after editing the .in file.
#
#   scripts/lock-voice-env.sh            keep existing pins wherever they still satisfy the input
#   scripts/lock-voice-env.sh --upgrade  re-resolve everything to the newest allowed versions
#
# It resolves with the same pinned uv the app carries (scripts/fetch-uv.sh), for
# the Python and the macOS floor conch supports, in a throwaway uv cache. The
# first lock was resolved against the freeze of the environment proven working
# on 2026-09-27 (95 packages), and matched it package for package.
#
# The daemon installs the result with --require-hashes, and a test holds the
# lock to its rules (test/voice-env.test.ts): loguru present, Python >= 3.10.
set -euo pipefail
cd "$(dirname "$0")/.."

# uv-managed CPython. mlx-audio needs >= 3.10: its dsp.py uses `X | Y` types,
# which is how an environment built on the system's Python 3.9 broke.
VOICE_PYTHON=3.12
# conch.app's MACOSX_DEPLOYMENT_TARGET: wheels must install on the oldest macOS it runs on.
MACOS_FLOOR=14.0
OUT=src/voice-requirements.txt

UV="$(scripts/fetch-uv.sh)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
# The existing lock is uv's preference list, so an unchanged input re-resolves to unchanged pins.
if [[ -f "$OUT" ]]; then grep -v '^# conch-' "$OUT" > "$work/lock.txt"; fi

MACOSX_DEPLOYMENT_TARGET="$MACOS_FLOOR" UV_CACHE_DIR="$work/cache" UV_NO_CONFIG=1 \
  "$UV" pip compile src/voice-requirements.in \
    --python-version "$VOICE_PYTHON" \
    --python-platform aarch64-apple-darwin \
    --generate-hashes \
    --no-header \
    --quiet \
    --output-file "$work/lock.txt" \
    "$@"

{
  echo "# conch-lock: natural voices (Kokoro via mlx-audio). Generated by scripts/lock-voice-env.sh"
  echo "# conch-lock: from src/voice-requirements.in — edit that file, then re-run the script."
  echo "# conch-voice-python: $VOICE_PYTHON"
  echo "# conch-voice-platform: macOS $MACOS_FLOOR+ arm64 (MLX runs only on Apple silicon)"
  cat "$work/lock.txt"
} > "$OUT"
echo "wrote $OUT ($(grep -cE '^[A-Za-z0-9]' "$OUT") packages)"
